# Generated by Django 4.1.4 on 2023-12-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="BirthDate",
            field=models.DateField(auto_created=True, default="1990-01-01"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="City",
            field=models.CharField(default="", max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Country",
            field=models.CharField(default="India", max_length=15, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=1
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="Pincode",
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="State",
            field=models.CharField(default="", max_length=20, null=True),
        ),
    ]
