# Generated by Django 4.1.4 on 2023-12-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0002_userprofile_birthdate_userprofile_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Country",
            field=models.CharField(default="", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("f", "female"), ("m", "male")], default="", max_length=1
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Pincode",
            field=models.CharField(default="", max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="State",
            field=models.CharField(default="", max_length=25, null=True),
        ),
    ]
