# Generated by Django 4.1.4 on 2024-01-02 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0003_alter_userprofile_country_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="master",
            name="Email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=2
            ),
        ),
    ]
