# Generated by Django 5.0 on 2024-01-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0004_alter_master_email_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(default="avatar.png", upload_to="profile_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("f", "female"), ("m", "male")], default="", max_length=2
            ),
        ),
    ]
