# Generated by Django 4.1.4 on 2024-01-09 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0005_userprofile_profileimage_alter_userprofile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuesAns",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "QuesImage",
                    models.FileField(default="avtar.png", upload_to="ques_images/"),
                ),
                ("Question", models.TextField(max_length=2500)),
                ("Options", models.TextField(max_length=2500)),
                ("IsMultiSelect", models.BooleanField(default=False)),
                ("Answer", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="QuizCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("category", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="QuizPlay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Score", models.IntegerField()),
                (
                    "RemarkLevel",
                    models.CharField(
                        choices=[
                            ("25", "Poor"),
                            ("50", "Average"),
                            ("75", "Good"),
                            ("100", "Excellent"),
                        ],
                        max_length=25,
                    ),
                ),
                (
                    "QuesAns",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.quesans",
                    ),
                ),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.userprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=100)),
                ("Duration", models.IntegerField(default=0)),
                (
                    "DifficultyLevel",
                    models.CharField(
                        choices=[("easy", "easy"), ("mid", "medium"), ("hrd", "hard")],
                        max_length=25,
                    ),
                ),
                ("TotalScore", models.IntegerField()),
                (
                    "UserProfile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.userprofile",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.quizcategory",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="quizApp.subject",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="quesans",
            name="Quiz",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="quizApp.quiz"
            ),
        ),
    ]
