# Generated by Django 4.1.4 on 2024-01-09 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0006_quesans_quizcategory_subject_quizplay_quiz_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="quesans",
            options={"verbose_name_plural": "Ques n Answers"},
        ),
        migrations.AlterModelOptions(
            name="quiz",
            options={"verbose_name_plural": "Quizes"},
        ),
        migrations.AlterField(
            model_name="quiz",
            name="DifficultyLevel",
            field=models.CharField(
                choices=[("easy", "Easy"), ("mid", "Medium"), ("hrd", "Hard")],
                max_length=25,
            ),
        ),
    ]
