# Generated by Django 4.1.4 on 2024-03-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0007_alter_quesans_options_alter_quiz_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesans",
            name="QuesImage",
            field=models.FileField(default="user.png", upload_to="ques_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=2
            ),
        ),
    ]
