# Generated by Django 4.1.4 on 2024-03-24 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0008_alter_quesans_quesimage_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesans",
            name="QuesImage",
            field=models.FileField(default="user", upload_to="ques_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("f", "female"), ("m", "male")], default="", max_length=2
            ),
        ),
    ]
