# Generated by Django 4.1.4 on 2024-03-24 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0009_alter_quesans_quesimage_alter_userprofile_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesans",
            name="QuesImage",
            field=models.FileField(default="user.png", upload_to="ques_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(default="user.png", upload_to="profile_images/"),
        ),
    ]
