# Generated by Django 4.1.4 on 2024-03-24 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0010_alter_quesans_quesimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quesans",
            name="QuesImage",
            field=models.FileField(default="avatar.png", upload_to="ques_images/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(
                default="uploads/profile_images/user.png", upload_to="profile_images/"
            ),
        ),
    ]
