# Generated by Django 4.1.4 on 2024-03-24 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0011_alter_quesans_quesimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(
                default="uploads/user.png", upload_to="profile_images/"
            ),
        ),
    ]
