# Generated by Django 4.1.4 on 2024-03-24 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0012_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(
                default="E:/Logic Rays/Quiz p1/uploads/user.png",
                upload_to="profile_images/",
            ),
        ),
    ]
