# Generated by Django 4.1.4 on 2024-03-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0013_alter_userprofile_profileimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("f", "female"), ("m", "male")], default="", max_length=2
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="ProfileImage",
            field=models.FileField(default="user.png", upload_to="profile_images/"),
        ),
    ]
