# Generated by Django 4.1.4 on 2024-03-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quizApp", "0014_alter_userprofile_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quiz",
            old_name="category",
            new_name="Category",
        ),
        migrations.RenameField(
            model_name="quiz",
            old_name="subject",
            new_name="Subject",
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="Gender",
            field=models.CharField(
                choices=[("m", "male"), ("f", "female")], default="", max_length=2
            ),
        ),
    ]
