# Generated by Django 6.0 on 2026-09-05 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0015_rename_category_quiz_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='BirthDate',
            field=models.DateField(default='1990-01-01'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='', max_length=2),
        ),
    ]
